#+TITLE:     
#+AUTHOR:    David Mann
#+EMAIL:     mannd@epstudiossoftware.com
#+DATE:      [2020-07-31 Fri]
#+DESCRIPTION: EP Diagram Help
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+HTML_HEAD: <style media="screen" type="text/css"> img {max-width: 100%; height: auto;} </style>
#+HTML_HEAD: <style  type="text/css">:root { color-scheme: light dark; }</style>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./org.css"/>
* Development Version Notes
EP Diagram is under active development, but this version is now feature complete, and the remaining development will be bug fixes and usability improvements.
** New in this version
- This version's file format is compatible with previous alpha versions.
- This is the last alpha version.  Next version will be first beta for general testing.
- Mark linking and unlinking are improved, and undo now correctly recreates previous app states.
- Double-tap deletes marks in Edit mode.
- Impulse origin automatic analysis improved.
- Bug fixes.
** What is still missing
- Documentation of the app in this help file.
- Onboarding, tooltips.
- Final file format will probably NOT be backward compatible with current file format.
- More bug fixes.
** Quick Start
*** Normal mode
- EP Diagram opens and saves diagram files, that will be stored in the files app on you iPad or iPhone.
- When you open or create a new diagram file, you will see a blank area at the top of the screen and a default ladder grid at the bottom.
- Use the "hamburger" menu icon at the top left to open the menu.  You can select an image from your photos or your files and it will appear in the top of the screen.
- Tap on the image to create marks.  Use the cursor to align the mark with the ECG waveforms.  Tap away from the cursor to hid the cursor.  Tap on a mark to show the cursor and each tap changes the movement point of the mark from middle to proximal to distal.
- Double click on a mark to delete it.  Double click anywhere else to create a mark.  Double clicking is a fast way to create marks.
- Marks appear in the active region, shown by a colored background.  If you tap on a different region the marks will appear in that region and the active region will change.  Tapping on the label of the region will also activate or deactivate the region.
- Dragging in a region will also create a mark.
- Long press on the cursor to change it to an omnidirectional cursor (it has a large circle on it), allowing marks to move in any direction.  Long press again to change it back.
- Marks that are placed end to end will automatically link up and move together afterwards.
*** Calibration mode
- Press the Calibrate button to show a caliper that can be used to calibrate the diagram to a standard interval of 1000 msec.
- After calibration, measurements will appear on the diagram.
*** Edit mode
- Press Edit to allow taps to select marks or regions, or dragging to select zones.
- Long press after selection to show a menu that allows extensive customization of the appearance of the marks, including the style, emphasis, block, impulse origin, etc. and also allows adding a rhythm to a region or zone, e.g. atrial fibrillation.
*** Connect mode
- Tap pairs of marks separated by a region to connect the marks.
- Tap from a mark to an adjacent region to have a mark block in that region.
*** Undo/Redo
- Practically anything you do can be undone or redone and these changes are automatically saved.
** Other features
*** Select ladders
*** Edit/Create your own ladders
*** Sample diagrams
*** Preferences
- Change the overall appearance or behavior of the app.
* Known issues/bugs 
- Close marks can be difficult to individually select.
- Diagram document format likely to change in release version and be incompatible with present format.
- Need more sample ECGS.
- Mac version to be done.  Need to convert menu system to Mac.
- Help file for release version not done.
