#+TITLE:     
#+AUTHOR:    David Mann
#+EMAIL:     mannd@epstudiossoftware.com
#+DATE:      [2021-04-09 Fri]
#+DESCRIPTION: EP Diagram Help
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil ::t |:t ^:t -:t f:t *:t <:t

#+OPTIONS:   d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+HTML_HEAD: <style media="screen" type="text/css"> img {max-width: 100%; height: auto;} </style>
#+HTML_HEAD: <style  type="text/css">:root { color-scheme: light dark; }</style>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./org.css"/>


* Click the /Import image/ toolbar button to add an image to your diagram
- You can load images from your photos or from any image file, including PDF files.

* Pan and zoom the image
- Pan and pinch to zoom using a trackpad, or click on the zoom buttons in the toolbar.

* Click the /Connect/ button to connect marks
- Click pairs of marks, or click a mark and an adjacent region to connect marks.

* Click the /Edit/ button to edit the ladder
- Click or click and drag to select regions and marks.  Then Control-click the ladder to open a menu with options to style marks, copy and paste, generate rhythms, and much more.  Also try Control-clicking the ladder labels and image while in Edit mode.

* Click the /Calibrate/ button to calibrate your diagram
- After calibration, intervals and conduction times will appear on your diagram.

* Autosave and the /Undo/ and /Redo/ buttons
- All changes are automatically saved.  Click the /Undo/ and /Redo/ toolbar buttons to revert and restore your changes.  Click the /Close Diagram/ button at the top right of the toolbar to close your diagram.

* Play around and experiment
- There are a lot of features to explore.  Use the /EP Diagram Help/ menu item to learn new features.

* That's it! Click the Done button to begin using *EP Diagram*


